### ISSUE TITLE
No messages send when errors in one feed

### ISSUE THREAD

**Issue by maltechx** [0x111/telegram-rss-bot#1]
Im getting the follwing errors and when I removed feedID=2 it seemed to start working again.
````
INFO[3200] Updating feeds                                feedID=1 feedUrl="https://rss.golem.de/rss.php"
2020/05/29 12:14:59 sendMessage resp: {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 197"}
ERRO[3200] There was an error while posting the update to the feed!  chatID=43919129 error="Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 197" feedPost="{7 2 Am Freitag online: WeAreDevelopers Live Week – u.a. mit GraphQL und Chatbots https://www.heise.de/news/Am-Freitag-online-WeAreDevelopers-Live-Week-u-a-mit-GraphQL-und-Chatbots-4726708.html?wt_mc=rss.red.ho.top-news.atom.beitrag.beitrag false 0001-01-01 00:00:00 +0000 UTC 43919129}"
2020/05/29 12:14:59 sendMessage resp: {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 145"}
ERRO[3200] There was an error while posting the update to the feed!  chatID=43919129 error="Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 145" feedPost="{8 2 Automatisierte Sicherheit für autonome Fahrzeuge https://www.heise.de/news/Automatisierte-Sicherheit-fuer-autonome-Fahrzeuge-4768764.html?wt_mc=rss.red.ho.top-news.atom.beitrag.beitrag false 0001-01-01 00:00:00 +0000 UTC 43919129}"
INFO[3200] Updating feeds                                feedID=2 feedUrl="https://www.heise.de/rss/heise-top-atom.xml"
````

**Comment by 0x111** [comment]
Thank you for using the app!

Is this something happening regularly? Or just at some random occasions?
~~Because 400 means Bad request HTTP code and what I am thinking is, that this might be caused by some short outage to the generation of the XML feed.~~

~~Because based on the error it really seems that there is some partial XML only or that the returned XML is not complete for some reason.~~

Edit: This is returned from the telegram API, so scrap that what I've said...
We are using markdown syntax, so there might be that some of the markdown tags are not closed and that is what Is causing the issue in this case.

**Comment by maltechx** [comment]
Just started using the app, so I need to watch it a little more.
But for now I removed the feed from heise.de and I got messages from all other feeds.
Another feed is also creating an error but not two errors at one time and its not causing the bot to stop completely.
```
2020/05/29 13:11:39 sendMessage resp: {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 117"}
ERRO[6600] There was an error while posting the update to the feed!  chatID=43919129 error="Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 117" feedPost="{25 5 Samsung Notebooks: Drei neue Galaxy Books vorgestellt http://feedproxy.google.com/~r/stadt-bremerhaven/dqXM/~3/Ca_MljFKrB8/ false 2020-05-29 07:59:19 +0000 UTC 43919129}"
```

**Comment by 0x111** [comment]
I think this could be solved with turning off markdown parsing. I do not use it anyways and RSS feeds do not use it either, no idea why that was left there. I will create a PR soon.

**Comment by maltechx** [comment]
Thanks for looking into that, I appreciate that!

**Comment by 0x111** [comment]
@maltechx One more question, what did you set as your Feed name? While using the `/add` command?
Please look in the history, I am using Markdown there, so that may cause the issue, why it is not able to resolve this.

**Comment by 0x111** [comment]
I've found the issue from your debug output. Great that you've provided those! Thank you!

**Comment by 0x111** [comment]
@maltechx Hey, could you try to get the build artifacts here? https://github.com/0x111/telegram-rss-bot/actions/runs/119468497
These are the latest binaries with the changes I've made. The issue in your case was, that I was not correctly escaping all chars that could be treated as markdown (also I was using the first older version). So I've switched to markdownv2 now and implemented the escaping. So now it should be working fine.

The artifacts contain all versions, I do not know which one do you use, so let me know please!

**Comment by maltechx** [comment]
Okay got em. I'm using the linux-amd64 version.   
The new version is now running, so lets see how it works.

**Comment by 0x111** [comment]
@maltechx How does it look? Any errors or issues?

**Comment by maltechx** [comment]
Looks good so far, no errors poped up. 
But Telegram is now asking, if I want to open the link:
![](https://images.maltechx.de/file/f0e2073168f36d0a63b30dd9.png)

Thanks a lot, it's working perfectly so far!

**Comment by 0x111** [comment]
Great! Thanks for the using the app, in any case if you encounter some issues feel free to raise them!

The same counts for feature requests if any. I am using this for some feeds, I am fine with it for now, but if there are some things that could be improved or make life less complicated, then I am up for it!
