### ISSUE TITLE
HEROKU ?

### ISSUE THREAD

**Issue by IshwaranRudhara** [0x111/telegram-rss-bot#18]

**Comment by 0x111** [comment]
I don't think that we can run this app on heroku. This is not some API that you can call periodically and do some tasks, in fact, there is no API except of the commands on telegram.

**Comment by IshwaranRudhara** [comment]
> I don't think that we can run this app on heroku. This is not some API that you can call periodically and do some tasks, in fact, there is no API except of the commands on telegram.

sir contact me from channell!!
