### ISSUE TITLE
K8s/OpenShift deployment

### ISSUE THREAD

**Issue by slaterx** [0x111/telegram-rss-bot#3]
First of all, thank you very much for working on this and sharing with the community. I was looking for something on golang for maintaining RSS feeds on Telegram, but ended up wasting my time on not so useful things in other language.

I took your code and made changes to make it deployable on k8s/OpenShift environments. Would you be interested in a PR with such changes?

**Comment by 0x111** [comment]
hi @slaterx thank you for using the app! I appreciate any feedback or improvements.

The question here is from my point of view, how does this benefit users in general. How could they use the app configured in this way?

Isn't the configuration for K8s/Openshift specific or can this be also used in conjunction with for example a simple docker container support?

**Comment by slaterx** [comment]
Hi,

The application would be available as a container in the exact way it would be available as a compiled executable in one's computer. There were no changes in the application itself for that matter.

For that to work, I only applied changes in the configuration JSON file to accept environment variables. Thus, one could package and/or use it it as a binary application with the sample config (by copying the sample JSON file) in a machine, or as either a plain docker container, a k8s container or an OpenShift element with the new templated configuration (by setting the environment variables). 

Since seeing is easier than explaining, I'll raise the PR and let you review and share your thoughts.

**Comment by slaterx** [comment]
Created PR #4.
