### ISSUE TITLE
Show feed name on messages

### ISSUE THREAD

**Issue by ghost** [0x111/telegram-rss-bot#5]
It's difficult to recognize what message is from which feed when subscribing to some social network service (for example, twitter which provide "rt", and it's link to the original post when using all 3rd party feed extractor I ever found).

**Comment by 0x111** [comment]
Thanks for your feedback!

Could you show some example maybe on how the current output could look that would be more useful in regards of user experience?

I am open to adding the feed name in the output, that is not really a problem. I am also accepting PR's if you want to give it a shot!

**Comment by ghost** [comment]
When using twitter feeds provided by rsshub.app, all rts will only show the original poster, it will also be useful when I want to filter some posts in a particular feed.

**Comment by 0x111** [comment]
Thanks for the answer.

So right now we are outputting the entries like this:
`{entry title} - {URL}`
Changing it to this:
`{feed name} - {entry title} - {URL}`

 I think this should make it more clear which feed this is about, any other suggestions?

**Comment by 0x111** [comment]
@L-iquor Could you please test the PR (there is a link there for the automatic build done here on github from the sources of the repo). Please download that archive and find your binary for the platform you use and test please.

I am using the name that was provided when you've added the feeds to the bot's database. This way you can easily distinguish which feed it is that it is coming from.
